### ISSUE TITLE
Login de usuarios al sistema.

### ISSUE THREAD

**Issue by MaxPhoenix** [tpfinal-pp1/tp-final#229]
_verificacion de credenciales de usuario.
_asignacion de privilegios de agente (vistas a las que tiene acceso)

**Comment by aikomisa5** [comment]
Cree varios administradores y agentes pero al momento de intentar ingresar al sistema me dice "credenciales sin acceso al sistema"

**Comment by MaxPhoenix** [comment]
sisis @agusalex  lo reviso hace un rato despues lo cambia

**Comment by agusalex** [comment]
jeje si pifie me falto la parte de agregar nuevos

**Comment by roberGzt** [comment]
fixed, pasado a QA para que misa ponga so seal of approval
![image.png](https://images.zenhubusercontent.com/59335e5851aa2c30578057b2/e02a3b34-5d9e-4d7a-b0b3-f14917a612a7)

**Comment by aikomisa5** [comment]
![image.png](https://images.zenhubusercontent.com/59c0646db0222d5de47835ea/8521c6b2-4ca7-4ea6-b76d-a91035f178d1) @agusalex ahora si!
