### ISSUE TITLE
INMUEBLES: Problema carga de combobox

### ISSUE THREAD

**Issue by aikomisa5** [tpfinal-pp1/tp-final#236]
![comboerror.gif](https://images.zenhubusercontent.com/59c0646db0222d5de47835ea/abf8e207-7e75-498f-b0f3-6e8e9e3b084e)Si por ejemplo uno quiere editar un inmueble que es de tipo inmobiliaria, o sea que tiene un propietario inmobiliaria, al momento de querer seleccionar otra inmobiliaria como dueña, en vez de mostrarse la lista de inmobiliarias disponibles, se muestran personas.

Recien se soluciona si uno destilda y vuelve a tildar el  checkbox de "Inmobiliaria"

**Comment by agusalex** [comment]
Mismo que 213
