### ISSUE TITLE
PUBLICACIONES: Bug al intentar crear publicaciones

### ISSUE THREAD

**Issue by aikomisa5** [tpfinal-pp1/tp-final#237]
![null pointer.gif](https://images.zenhubusercontent.com/59c0646db0222d5de47835ea/e1b4afa9-86d8-4ebb-8ce3-b67960fa9074)
ACT: El error es porque no elegis una fecha de celebración, tira ese mensaje y no uno amigable. Fecha de celebracion deberia ser campo obligatorio entonces?

**Comment by aikomisa5** [comment]
Sigue estando el mismo error, Danilo

**Comment by deidelson** [comment]
![screenshot_14](https://user-images.githubusercontent.com/23360628/32111939-5e1d0528-bb12-11e7-91a0-e72516e448eb.jpg)
mira

**Comment by aikomisa5** [comment]
Ahora sí.. eso que habia hecho refresh de la página varias veces
