### ISSUE TITLE
Crear pantalla de empleados

### ISSUE THREAD

**Issue by MaxPhoenix** [tpfinal-pp1/tp-final#239]
_grilla con datos de los empleados de la empresa 
_deben figurar los empleados con y  sin credenciales.
_figurar si se encuentran activos o no para ingresar al sistema
_credenciales en el registro de empleado.

**Comment by aikomisa5** [comment]
todo perfecto, solo falta que se muestre en pantalla si estan activos para ingresar al sistema o no (en el caso de que posean credenciales claro)

**Comment by MaxPhoenix** [comment]
sisi @agusalex  se iba a poner con eso, aun asi bien que lo hagas notar @aikomisa5

**Comment by roberGzt** [comment]
Respecto a eso, hay que dar de alta la credencial? porque yo recien probe de crear un agente inmobliario, su credencial correspondiente, me deslogueo y me tira un mensaje de "credenciales sin acceso al sistema"

**Comment by roberGzt** [comment]
Ah, debe ser que hay que asignarle las views. Proppongo como cambio que cuando se se le asigna un empleado a una credencial, esta automaticamente se asigne los view access correspondientes @agusalex

**Comment by roberGzt** [comment]
![image](https://user-images.githubusercontent.com/23635942/32233026-2f556cd4-be38-11e7-9738-1bde9aa1cbe8.png)

@aikomisa5  test me pls(?

**Comment by aikomisa5** [comment]
@roberGzt Ahora directamente no te deja dar de alta empleados. Al momento de escribir un nombre de usuario (cualquiera), te tira el mensaje de que ya existe dicho usuario entonces no te deja crearlo ![image.png](https://images.zenhubusercontent.com/59c0646db0222d5de47835ea/bef35868-e0b5-4640-96e9-7cf1de2e4962)

**Comment by roberGzt** [comment]
@aikomisa5 volvi a probar en el server y no me salta ese error :C, igual ahora pusheo unos cambios menores en el mensaje de guardado para que muestre el nombre de la persona y no el empleado.toString()
![testalta.gif](https://images.zenhubusercontent.com/59335e5851aa2c30578057b2/75140f98-179c-43e9-8c19-24ef8a4104c9)

**Comment by aikomisa5** [comment]
@roberGzt Lo malo que tiene ahora son 2 cosas: Si ingresas con un usuario administrador que hayas creado, te permite darte de baja a vos mismo, cosa que quiza podemos tomarlo como bug menor. Y lo segundo que si es mas critico quizás, es que cuando das de baja a alguien, y luego lo reincorporas, y queres volver a entrar a la app, no te deja. No te tira ningun cartel de error ni nada, pero vos le das click a ingresar y no hace nada de nada la app
