### ISSUE TITLE
Matching falla, causa desconocida

### ISSUE THREAD

**Issue by agusalex** [tpfinal-pp1/tp-final#254]
Deje todos los campos vacios salvo por los que se ve en el gif
![Matching falla.gif](https://images.zenhubusercontent.com/59b97b2bb0222d5de4779cbc/07d7c032-7aa1-4354-9b19-15728aed1d51)

**Comment by roberGzt** [comment]
Se probo en server y localhost y no se pudo reproducir. Es posible que los datos del generador con que se descubrio el bug estuvieran corruptos. con publicaciones creadas desde la ui no se evidencio el supuesto bug.
