### ISSUE TITLE
Actualizar valor de contrato al renovar

### ISSUE THREAD

**Issue by roberGzt** [tpfinal-pp1/tp-final#314]
![GIF PARA ROBER.gif](https://images.zenhubusercontent.com/59c0646db0222d5de47835ea/2c27ab81-eac1-42b2-a1b1-48f84257b46e)

**Comment by aikomisa5** [comment]
Tengo una duda con esto. Ponele que tengo un contrato de 24 meses, el intervalo de actualización es de cada 12 meses. El valor inicial es 100, y el aumento por actualización es del 10%, los intereses son simples. Al momento de renovar el contrato debería aparecerme como valor inicial 120$? @roberGzt

**Comment by roberGzt** [comment]
no se, en los cobros dado ese intervalo se actualiza 1 sola vez no? Osea, del mes 1 al 12 es un valor 1
del mes 13 al 24 al 24 es un valor 2. Si seguimos con esa progresión, a la hora de renovar (ya vencido, lo que corresponderia al mes 25, no lo veo mal que tenga un precio 3. Pero es debatible)

**Comment by roberGzt** [comment]
para ese ejemplo que diste es asi ahora:
1-12 ->100
13-24 -> 110
25-> renovación -> 120

Pero si cumplimos especificamente con el cambio como se pidio en realidad deberia arrancar con 110.

**Comment by aikomisa5** [comment]
@roberGzt porque hoy intente el ejemplo este que te digo y me dio que al intentar renovar me tiraba 120$

**Comment by aikomisa5** [comment]
@roberGzt ahi esta
