### ISSUE TITLE
PARAMETRIZACION: (Pagos, venc y intimaciones), configuracion de periodicidad de recordatorios (sistema por el momento) 

### ISSUE THREAD

**Issue by MaxPhoenix** [tpfinal-pp1/tp-final#324]
Periodicidad Regulable=PR, Periodicidad Automática=PA
1.Avisos Intimación -> 10 días antes Vencimiento;  PR: todos los dias por defecto
2.Abandono de inmueble–-> 10 días antes Vencimiento;  PR; por defecto 10 días .
3.Vencimiento Contrato ––> 1 Mes antes Vencimiento ;  PR; default 10 días.
4.Pago Vencido –-> 10 M antes Venc; PA. según calificación.

**Comment by agusalex** [comment]
mismo que 387
