### ISSUE TITLE
Bug:No se generan reportes de cobros por rangos ni del mes

### ISSUE THREAD

**Issue by roberGzt** [tpfinal-pp1/tp-final#358]
La ui de reportes no permite seleccionar un rango de fechas para reportes de alquileres.
Adicionalmente, ni el reporte de cobros por rangos ni el reporte de cobros del mes se genera. En su lugar se esta generando el reporte de propietarios.
![testReportes.gif](https://images.zenhubusercontent.com/59335e5851aa2c30578057b2/5e80c428-487b-4908-8b2a-7dc8d74cf676)

**Comment by aikomisa5** [comment]
@roberGzt Estaba viendo eso, y creo que sé porque puede ser. Debe ser que como cambiamos algunos atributos de string a bigdecimal, se perdieron las referencias del reporte de alquileres a cobrar.

**Comment by roberGzt** [comment]
En realidad, hay que crear un dto de items de reporte por cada tipo de reporte. Deberias dejar el anterior para el reporte por rangos y usar el modificado con bigdecimal para el que precisa de calculos monetarios.

**Comment by aikomisa5** [comment]
![image.png](https://images.zenhubusercontent.com/59c0646db0222d5de47835ea/98335d22-915d-4c17-a4c0-986b147152e0) En localhost me funca, ahora commiteo a ver que onda @roberGzt

**Comment by aikomisa5** [comment]
![image.png](https://images.zenhubusercontent.com/59c0646db0222d5de47835ea/c3f7d9ab-ac33-4899-be81-e3e9ecf811a9) @roberGzt

**Comment by aikomisa5** [comment]
Ya está. Lo que pasaba con el reporte de alquileres por mes, era que le habia puesto la fuente de calibri light, creyendo que no iba a tener problema, y al final por alguna razon el server lo rechaza, pero en localhost lo toma bien. Cambie la fuente por sanddif o algo asi como tienen los demas reportes. Y el reporte de alquileres a cobrar no funcionaba porque uno de los archivos .jasper era una version anterior se ve y no coincidian los archivos entre si. Lo dejo para que lo revisen

**Comment by aikomisa5** [comment]
Igual tengo un par de dudas sobre los valores que se muestran. Me hace ruido la clase dto que creamos para el reporte porque no se si estamos trayendo los datos que se piden. Por el tema de que hay como 3 metodos, uno de getintereses, getmonto y genmontorecibido, y eso confunde, habria que revisarlo despues
