### ISSUE TITLE
pantalla citas : pantallita de notificaciones buggy 

### ISSUE THREAD

**Issue by MaxPhoenix** [tpfinal-pp1/tp-final#400]
![notificaciones ui bug.gif](https://images.zenhubusercontent.com/59b95e1fb0222d5de47798be/84595df9-9dae-4f3c-81a2-ba857f56a80c)

**Comment by agusalex** [comment]
Fixeado hace rato ya

**Comment by agusalex** [comment]
No se pudo volver a repetir el bug, posiblemente fix?
