### ISSUE TITLE
Citas: Bug raro con el scroll y las citas x2

### ISSUE THREAD

**Issue by aikomisa5** [tpfinal-pp1/tp-final#431]
![bug raro citas.gif](https://images.zenhubusercontent.com/59c0646db0222d5de47835ea/309cf608-5f53-42fb-9846-bfe296e3e116) No se si solo me pasara a mi pero en el server cuando le das doble click a una cita de la lista de notificaciones a veces se "rompe" la pantalla

**Comment by agusalex** [comment]
me paso, ya lo reviso

**Comment by agusalex** [comment]
No se pudo volver a repetir el bug, posiblemente fix?
