### ISSUE TITLE
Modulo ingresos/egresos (contabilidad/movimientos)

### ISSUE THREAD

**Issue by MaxPhoenix** [tpfinal-pp1/tp-final#482]
Un Movimiento tiene:
Descripción(1)
Fecha(1)
Monto(1)
Tipo de movimiento(1)
Ingreso
Concepto Ingreso
Venta
Alquiler
Comisión
Otro
Egreso
Concepto Egreso
Pago a Propietarios
Impuestos
Otro (De forma Manual)

1.Si, se debe poder distinguir el monto e intereses al momento de hacer el pago, es
decir que ambos deben ser visibles
2. Si, cuando se genera un pago el mismo se registra automáticamente como ingreso
en el sistema, el mismo quedará asociado a el inquilino e inmueble que corresponda.
3. Sí, se calculan y registran de forma automática, se deben poder agregar otros tipos
de egreso de forma manual.

1.Si, se debe poder distinguir el monto e intereses al momento de hacer el pago, es
decir que ambos deben ser visibles
2. Si, cuando se genera un pago el mismo se registra automáticamente como ingreso
en el sistema, el mismo quedará asociado a el inquilino e inmueble que corresponda.
3. Sí, se calculan y registran de forma automática, se deben poder agregar otros tipos
de egreso de forma manual.

**Comment by roberGzt** [comment]
- [ ] añadir window resumen de ingresos/egresos totales, etc
