### ISSUE TITLE
Inmuebles-Publicaciones: Implentar el estado "Reservado"

### ISSUE THREAD

**Issue by aikomisa5** [tpfinal-pp1/tp-final#493]
Según la minuta de la RF1: ![image.png](https://images.zenhubusercontent.com/59c0646db0222d5de47835ea/67a77194-a3d5-46f8-9843-afd4a94e9bb3)

**Comment by roberGzt** [comment]
No existe un requerimiento que sea "reservar inmuebles" asi que es probable que dicho estado pueda ser descartado. Tampoco hay funcionalidad en el sistema asociada a dicho estado.
