### ISSUE TITLE
Pantalla Citas-Calendario: Falta de checkbox pedido en RF1

### ISSUE THREAD

**Issue by aikomisa5** [tpfinal-pp1/tp-final#496]
![image.png](https://images.zenhubusercontent.com/59c0646db0222d5de47835ea/b05857b9-e116-4ea3-8e65-3b988f0cc51b)

**Comment by agusalex** [comment]
que seria eso? onda que proposito tendria hacer un checkbox que te deje " no ver mas los eventos" no le veo el sentido. De donde salio este Req?

**Comment by aikomisa5** [comment]
@agusalex  ![image.png](https://images.zenhubusercontent.com/59c0646db0222d5de47835ea/4deaf0ac-8980-4192-adfc-69b3f2c5180c)

**Comment by aikomisa5** [comment]
@agusalex la verdad es que no se para que se serviria. Yo no le veo sentido, solo lo puse porque maxi me dijo que revise la minuta y agregue todo lo que falta, si no lo pongo maxi me cuelga

**Comment by agusalex** [comment]
okeydokey
