### ISSUE TITLE
UI Parametros ABM (Sellado de Banco)

### ISSUE THREAD

**Issue by agusalex** [tpfinal-pp1/tp-final#514]
Lo ideal seria hacer que te habra una ventana desde la ventana de parametros en vez de crear una view mas como la de duracion.
44.7 Sellado de banco:
[Descripción: cadena de caracteres ,
Provincia: cadena de caracteres,
Porcentaje :número decimal] ->
valor por defecto ->

BuenosAires ["Sellado Banco Provincia", "Buenos Aires", 1.2]
Porcentaje : 1.2 % Buenos aires como provicia de inmueble.
Resto de provincias : 0.0% (se pueden agregar porcentajes por defecto por provincia)

**Comment by roberGzt** [comment]
En realidad podemos crear una view Parametros del sistema con todos los parametros editables, y para aquellos que son abms que abra una window par ala gestion de ese parametro en particular. No puede ir directo en la view para los parametros de la cita me parece eso es para los parametros que el agente inmobiliario puede modificar. Este parametro en particular solo es editable (como las duraciones) por un admin
